class ImageNames {
  static const String splashBackground = "assets/images/splash_background.png";
  static const String cheeziousText = "assets/images/cheezious_text.png";
  static const String cheeziousLogo = "assets/images/cheezious_logo.png";
  static const String cheeziousLogoText =
      "assets/images/cheezious_logo_text.png";
  static const String slide1 = "assets/images/slide1.png";
  static const String arrowleft = "assets/images/arrow_left.png";
  static const String headset = "assets/images/headset.png";
  static const String apple = "assets/images/apple.png";
  static const String facebook = "assets/images/facebook.png";
  static const String google = "assets/images/google.png";
  static const String phoneBlack = "assets/images/phone-black.png";
  static const String chat = "assets/images/chat.png";
  static const String whatsapp = "assets/images/whatsapp.png";
  static const String homeUnselected = "assets/images/home_unselected.png";
  static const String homeSelected = "assets/images/home_selected.png";
  static const String searchSelected = "assets/images/search_selected.png";
  static const String searchUnselected = "assets/images/search_unselected.png";
  static const String tagSelected = "assets/images/tag_selected.png";
  static const String tagUnselected = "assets/images/tag_unselected.png";
  static const String shopSelected = "assets/images/shop_selected.png";
  static const String shopUnselected = "assets/images/shop_unselected.png";
  static const String qrscan = "assets/images/qrscan.png";
  static const String notification = "assets/images/bell.png";
  static const String addressMark = "assets/images/address_mark.png";
  static const String card = "assets/images/card.png";
  static const String explore = "assets/images/explore.png";
  static const String gift = "assets/images/gift.png";
  static const String logout = "assets/images/logout.png";
  static const String personStar = "assets/images/person_star.png";
  static const String phoneWhite = "assets/images/phone_white.png";
  static const String track = "assets/images/track.png";
  static const String wallet = "assets/images/wallet.png";
  static const String box = "assets/images/box.png";
  static const String logoTransparent = "assets/images/logo_transparent.png";
  static const String whatsappOutlined = "assets/images/whatsapp_outlined.png";
  static const String phoneSecondary = "assets/images/phone_secondary.png";
}
